name: Generate CV PDF

on:
  push:
    branches:
      - master
    paths:
      - 'ilarion.kovalchuk.cv.md'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: generate-cv-pdf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Pandoc
        uses: pandoc/actions/setup@main

      - name: Install LaTeX
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: texlive-xetex texlive-fonts-recommended fonts-liberation
          version: 1

      - name: Convert Markdown to PDF
        run: |
          pandoc ilarion.kovalchuk.cv.md \
            -o ilarion.kovalchuk.cv.pdf \
            --pdf-engine=xelatex \
            --template=cv-template.tex

      - name: Publish PDF to `pdf` branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan pdf-tmp
          git rm -rf --cached . > /dev/null
          git add -f ilarion.kovalchuk.cv.pdf
          git commit -m "Auto-update CV PDF"
          git push -f origin pdf-tmp:pdf
