name: Generate CV PDF

on:
  push:
    branches:
      - master
    paths:
      - 'ilarion.kovalchuk.cv.md'

permissions:
  contents: write

concurrency:
  group: generate-cv-pdf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Pandoc
        uses: pandoc/actions/setup@main

      - name: Install LaTeX
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: texlive-xetex texlive-fonts-recommended fonts-liberation
          version: 1

      - name: Convert Markdown to PDF
        run: |
          pandoc ilarion.kovalchuk.cv.md \
            -o ilarion.kovalchuk.cv.pdf \
            --pdf-engine=xelatex \
            --template=cv-template.tex

      - name: Commit PDF
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Auto-update CV PDF"
          file_pattern: "ilarion.kovalchuk.cv.pdf"
